micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8082
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretKeyLaterOnAndPutInItSecretManagerOfCloudProvider

hello:
  controller:
    path: "/helloFromConfig"
  config:
    greeting:
      de: "Halo"
      en: "Hello"
jackson:
  property-naming-strategy: KEBAB_CASE
  generator:
    writeNumbersAsStrings: true
  serialization:
    writeDatesAsTimestamps: false
    writeDateTimestampsAsNanoseconds: false

flyway:
  datasources:
    default:
      enabled: true
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
      user: ${PG_USERNAME:postgres}
      password: ${PG_PASSWORD:secret}
      clean-schema: false
      schemas: mn
      default-schema: mn

datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - "com.mn.broker.persistence"
    properties:
      hibernate:
        show_sql: false